# Generated by Django 5.2.3 on 2025-06-16 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_client_company_remove_client_siret_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='client',
        ),
        migrations.AddField(
            model_name='client',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.company'),
        ),
    ]
