# Generated by Django 5.2.3 on 2025-06-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_company_client_client_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='siret',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
